
clean: true
preprocess_args:
  combine:
    metric:
      coordination: 
        name: mean_avg_coordination
      catch: 
        name: mean_avg_catch
      diff: 
        name: mean_reward
        agent_type: ci
    coll_coordination:
      a_rewards_weights: 
        shared_weights: [both, ci_only]
        reward: [ai_coll_ci_coll_zero_sum, ai_ind_ci_coll_zero_sum]
      b_rewards: 
        shared_weights: [ai_only, neither]
        reward: [ai_coll_ci_coll_zero_sum, ai_ind_ci_coll_zero_sum]
      c_weights: 
        shared_weights: [both, ci_only]
        reward: [ai_coll_ci_ind_zero_sum, ai_ind_ci_ind_zero_sum]
      d_none: 
        shared_weights: [ai_only, neither]
        reward: [ai_coll_ci_ind_zero_sum, ai_ind_ci_ind_zero_sum]
    coll_catch:
      a_rewards_weights: 
        shared_weights: [both, ai_only]
        reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum]
      b_rewards: 
        shared_weights: [ci_only, neither]
        reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum]
      c_weights: 
        shared_weights: [both, ai_only]
        reward: [ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
      d_none: 
        shared_weights: [ci_only, neither]
        reward: [ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
plot_args:
  - 
    selectors:
      mode: train
      coll_coordination: [b_rewards]
      coll_catch: [a_rewards_weights]
      metric: [catch, coordination]
    grid: [lr]
    hue: metric
    # style: lr
    name: objective
  - 
    selectors:
      mode: train
      lr: 0.0001
      agents: mean
      name: [stick_to_color, max_freq]
      coll_coordination: [b_rewards]
      coll_catch: [a_rewards_weights]
    grid: [name]
    hue: agent_type
    # style: name
    name: action
  # - 
  #   selectors:
  #     agents: [agent_0, agent_1, agent_2, agent_3, agent_4]
  #     name: [ind_coordination]
  #     reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum, ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
  #   grid: [reward, shared_weights]
  #   hue: lr
  #   style: agents
  #   name: agents
  # - 
  #   selectors:
  #     mode: train
  #     reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum, ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
  #   grid: [reward, shared_weights]
  #   hue: metric
  #   style: lr
  #   name: mean
  # - 
  #   selectors:
  #     agents: [agent_0, agent_1, agent_2, agent_3, agent_4]
  #     name: [ind_coordination]
  #     reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum, ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
  #   grid: [reward, shared_weights]
  #   hue: lr
  #   style: agents
  #   name: agents
  # - 
  #   selectors:
  #     agents: mean
  #     mode: train
  #     name: [stick_to_color, max_freq]
  #     reward: [ai_coll_ci_coll_zero_sum, ai_coll_ci_ind_zero_sum, ai_ind_ci_coll_zero_sum, ai_ind_ci_ind_zero_sum]
  #   grid: [reward, shared_weights]
  #   hue: name
  #   style: lr
  #   name: actions_mean
