exec:
  command: train
  script_name: gpu
labels:
  project: ai_vs_ci
  batch: madqn_tabular_vs_deep
  deep_agent_type: ci
grid:
  - 
    - params.env_args.rewards_args:
        ai:
          ind_coordination: 0
          avg_coordination: -1
          ind_catch: 0
          avg_catch: 1
        ci:
          ind_coordination: 0
          avg_coordination: 1
          ind_catch: 0
          avg_catch: -1
      labels.reward: ai_coll_ci_coll_zero_sum
  - params.agent_types.ai.controller_args.alpha: [0.001, 0.01,  0.1]
    labels.alpha: [0.001, 0.01,  0.1]
  - params.agent_types.ci.controller_args.opt_args.lr: [0.01, 0.001, 0.0001]
    labels.lr: [0.01, 0.001, 0.0001]
params:
  device_name: cuda
  scheduler_args:
    episodes: 10000
    eval_period: 10
    eval_setting:
      eps:
        ci: 0.0
        ai: 0.0
      training: 
        ci: false
        ai: false
    phases:
      - episode: 0
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training: 
            ci: true
            ai: true
  agent_types:
    ai:
      controller_args:
        alpha: 0.05
        gamma: 0.8
        q_start: 0
        obs_map: product
        cache_size: 1
        share_table: false
      controller_class: tabularq
    ci:
      controller_args:
        gamma: 0.80
        batch_size: 10
        target_update_freq: 100
        memory_args: 
          capacity: 100
          episode_length: 50
        model_args:
          net_type: gru
          hidden_size: 100
          multi_type: individual_weights
        opt_args:
          lr: 0.001
      controller_class: madqn
  writer_args:
    flush_period: 100000
    periods:
      trace: 10
      mean_trace: 1
      env: 1000
  env_class: adversial_graph_coloring
  env_args:
    ai_obs_mode: neighbors
    all_agents: 20
    fixed_agents: 0
    fixed_length: true
    fixed_network: false
    fixed_pos: false
    fixed_mapping: false
    graph_args:
      chromatic_number: 4
      degree: 4
      graph_type: random_regular
    max_steps: 50
    rewards_args:
      ai:
        avg_catch: 0
        avg_coordination: 0
        ind_catch: 1
        ind_coordination: 0
      ci:
        avg_catch: 0
        avg_coordination: 0
        ind_catch: 0
        ind_coordination: 1
