
clean: true
preprocess_args:
  combine:
    metric:
      coordination: 
        name: mean_avg_coordination
      catch: 
        name: mean_avg_catch
      diff: 
        name: mean_reward
        agent_type: ci
plot_args:
  - 
    selectors:
      mode: train
      lr: 0.0001
    grid: [metric, n_seeds]
    hue: correlated
    # style: correlated
    name: mean
  # - 
  #   selectors:
  #     agent_type: ci
  #     agents: mean
  #     mode: train
  #     name: [stick_to_color, max_freq]
  #   grid: [architecture]
  #   hue: name
  #   style: lr
  #   name: actions_mean
