grid:
  - - params.environment_args.reward_args:
        ci:
          ind_anticoordination:
            ci: 1
          ind_crosscoordination:
            ai: -1
        ai:
          ind_anticoordination:
            ci: -1
          ind_crosscoordination:
            ai: 1
      labels.rewards: individual
    - params.environment_args.reward_args:
        ci:
          global_anticoordination:
            ci: 1
          global_crosscoordination:
            ai: -1
        ai:
          global_anticoordination:
            ci: -1
          global_crosscoordination:
            ai: 1
      labels.rewards: global
  - params.controller_args.ai.wrapper_args.weight_sharing: [true, false]
    labels.ai_weights: [shared, individual]
  - params.controller_args.ci.wrapper_args.weight_sharing: [true, false]
    labels.ci_weights: [shared, individual]
  - params.controller_args.ci.opt_args.lr: [0.001, 0.0001]
    params.controller_args.ai.opt_args.lr: [0.001, 0.0001]
    labels.lr: [0.001, 0.0001]
include:
  - baseconfigs/train/cuda_v2.yml
  - baseconfigs/train/envs/erdos_renyi_40_v1.yml
  - baseconfigs/train/controller/pooling_full_v1.yml
  - baseconfigs/train/controller/madql_slow_v1.yml
  - baseconfigs/train/observer/neighbors_simple_v1.yml
  - baseconfigs/train/scheduler/10000_v1.yml
