selector_args:
    eps_start: 0.9
    eps_end: 0.05
    eps_decay: 200
replay_memory: 10000
opt_args:
    batch_size: 128
    gamma: 0.999
train_args:
    target_update: 2
    eval_period: 2
    num_episodes: 10
env_args:
    n_agents: 20
    graph_type: cycle
    max_steps: 100
    global_reward_fraction: 0.5