selector_args:
    eps_start: 0.9
    eps_end: 0.01
    eps_decay: 400
replay_memory: 10000
opt_args:
    batch_size: 128
    gamma: 0.999
train_args:
    target_update: 10
    eval_period: 20
    num_episodes: 1000