grid:
  - - params.controller_args.ai.wrapper_args.net_type: pooling_gru
      params.controller_args.ai.model_args:
        linear1: true
        rnn1: true
        linear2: true
        rnn2: true
        hidden_size: 100
        pooling_types: ["sum"]
      params.controller_args.ci.wrapper_args.net_type: pooling_gru
      params.controller_args.ci.model_args:
        linear1: true
        rnn1: true
        linear2: true
        rnn2: true
        hidden_size: 100
        pooling_types: ["sum"]
      labels.architecture: pooling_gru
    - params.controller_args.ai.wrapper_args.net_type: gru
      params.controller_args.ai.model_args:
        hidden_size: 100
      params.controller_args.ci.wrapper_args.net_type: gru
      params.controller_args.ci.model_args:
        hidden_size: 100
      labels.architecture: gru
  - params.controller_args.ai.wrapper_args.weight_sharing: [true, false]
    labels.ai_weights: [shared, individual]
  - params.controller_args.ci.wrapper_args.weight_sharing: [true, false]
    labels.ci_weights: [shared, individual]
include:
  - baseconfigs/train/cuda_repro_v1.yml
  - baseconfigs/train/envs/random_repro_v1.yml
  - baseconfigs/train/envs/reward_global_v1.yml
  - baseconfigs/train/controller/madql_slow_v1.yml
  - baseconfigs/train/observer/neighbors_simple_v1.yml
  - baseconfigs/train/scheduler/10000_v1.yml
