labels:
  project: ai_vs_ci
  batch: dev_linear_ad
params:
  agent_types:
    ci:
      selector_args:
        eps_start: 0.20
        eps_end: 0.20
        eps_decay: 2000
      controller_args:
        gamma: 0.999
        cache_size: 2
        model_args:
          net_type: rnn
          hidden_size: 10
          multi_type: shared_weights
          # multi_type: individual_weights
        opt_args:
          lr: 0.001
      controller_class: maq
    ai:
      selector_args:
        eps_start: 0.20
        eps_end: 0.20
        eps_decay: 2000
      controller_args:
        alpha: 0.05
        gamma: 0.999
        q_start: 0
        obs_map: product
        cache_size: 2
        share_table: true
      controller_class: tabularq
  train_args:
    eval_period: 10
    num_episodes: 100
  writer_args:
    periods:
      # video: 250
      trace: 10
      individual_trace: 100
      final: 1
      # table: 250
  env_class: table_game
  env_args:
    rewards:
      ai: 
        - [-1, -3]
        - [0, -2]
      ci: 
        - [-1, -3]
        - [0, -2]