exec:
  command: train
  script_name: gpu
labels:
  project: ai_vs_ci
  batch: learning_latency
grid:
  - - params.controller_args.ci.target_update_freq: 1
      params.controller_args.ci.sample_args.batch_size: 1
      params.controller_args.ci.sample_args.horizon: 1
      labels.stabilizing: quick
    - params.controller_args.ci.target_update_freq: 10
      params.controller_args.ci.sample_args.batch_size: 1
      params.controller_args.ci.sample_args.horizon: 1
      labels.stabilizing: small
    - params.controller_args.ci.target_update_freq: 10
      params.controller_args.ci.sample_args.batch_size: 10
      params.controller_args.ci.sample_args.horizon: 50
      labels.stabilizing: medium
    - params.controller_args.ci.target_update_freq: 100
      params.controller_args.ci.sample_args.batch_size: 10
      params.controller_args.ci.sample_args.horizon: 50
      labels.stabilizing: slow_update
    - params.controller_args.ci.target_update_freq: 10
      params.controller_args.ci.sample_args.batch_size: 40
      params.controller_args.ci.sample_args.horizon: 100
      labels.stabilizing: big_batch
    - params.controller_args.ci.target_update_freq: 10
      params.controller_args.ci.sample_args.batch_size: 10
      params.controller_args.ci.sample_args.horizon: 500
      labels.stabilizing: far_horizon
  - params.controller_args.ci.opt_args.lr: [0.001, 0.0001]
    params.controller_args.ai.opt_args.lr: [0.001, 0.0001]
    labels.lr: [0.001, 0.0001]
params:
  seed: null
  device_name: cuda
  save_interval:
    train: 10
    eval: 1
  scheduler_args:
    episodes: 15000
    eval_period: 10
    eval_setting:
      eps:
        ci: 0.0
        ai: 0.0
      training:
        ci: false
        ai: false
    phases:
      - episode: 0
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training:
            ci: true
            ai: false
      - episode: 3000
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training:
            ci: false
            ai: true
      - episode: 6000
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training:
            ci: true
            ai: false
      - episode: 9000
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training:
            ci: false
            ai: true
      - episode: 12000
        setting:
          eps:
            ci: 0.1
            ai: 0.1
          training:
            ci: true
            ai: true
  environment_args:
    class_name: network_game
    n_nodes: 20
    n_actions: 4
    episode_steps: 20
    max_history: 5000
    network_period: 1
    graph_args:
      constrains:
        max_max_degree: 8
        connected: True
      graph_args:
        p: 0.2
      graph_type: erdos_renyi
    reward_args:
      ci:
        ind_anticoordination:
          ci: 1
        ind_crosscoordination:
          ci: -1
      ai:
        ind_anticoordination:
          ci: -1
        ind_crosscoordination:
          ci: 1
    agent_type_args:
      ci:
        mapping_type: fixed
      ai:
        mapping_type: fixed
    control_args:
      correlated: True
      cross_correlated: True
      n_control: 8
  observer_args:
    ci:
      class_name: neighbor
      neighbor_view_args:
        actions_view: ["ci"]
    ai:
      class_name: neighbor
      neighbor_view_args:
        actions_view: ["ci"]
  controller_args:
    ai:
      class_name: madqn
      gamma: 0.80
      target_update_freq: 2
      sample_args:
        batch_size: 5
        horizon: 100
      opt_args:
        lr: 0.001
      wrapper_args:
        weight_sharing: false
        net_type: pooling_gru
      model_args:
        linear1: true
        rnn1: true
        linear2: true
        rnn2: true
        hidden_size: 20
        pooling_types: ["avg", "max", "sum"]
    ci:
      class_name: madqn
      gamma: 0.80
      target_update_freq: 2
      sample_args:
        batch_size: 5
        horizon: 100
      opt_args:
        lr: 0.001
      wrapper_args:
        weight_sharing: True
        net_type: pooling_gru
      model_args:
        linear1: true
        rnn1: true
        linear2: true
        rnn2: true
        hidden_size: 20
        pooling_types: ["avg", "max", "sum"]
