labels:
  baseline: repro
include:
  - baseconfigs/train/cuda_repro_v1.yml
  - baseconfigs/train/envs/random_repro_v1.yml
  - baseconfigs/train/envs/reward_original_v1.yml
  - baseconfigs/train/controller/madql_repro_v1.yml
  - baseconfigs/train/observer/neighbors_simple_v1.yml
  - baseconfigs/train/scheduler/10000_v1.yml
