labels:
  project: ai_vs_ci
  batch: dev_linear_ad
params:
  scheduler_args:
    episodes: 100
    eval_period: 10
    eval_setting:
      eps:
        ci: 0.0
        ai: 0.0
      training: 
        ci: false
        ai: false
    phases:
      - episode: 0
        setting:
          eps:
            ci: 0.2
            ai: 0.2
          training: 
            ci: true
            ai: true
  run_args:
    num_threads: 1
  agent_types:
    ci:
      selector_args:
        eps_start: 0.20
        eps_end: 0.20
        eps_decay: 2000
      controller_args:
        gamma: 0.999
        cache_size: 2
        model_args:
          net_type: linear
          hidden_size: 10
          # multi_type: shared_weights
          multi_type: individual_weights
        opt_args:
          lr: 0.001
      controller_class: maq
    ai:
      selector_args:
        eps_start: 0.20
        eps_end: 0.20
        eps_decay: 2000
      controller_args:
        alpha: 0.05
        gamma: 0.999
        q_start: 0
        obs_map: product
        cache_size: 2
        share_table: true
      controller_class: tabularq
  writer_args:
    periods:
      # video: 250
      trace: 10
      individual_trace: 100
      final: 1
      # table: 250
  env_class: adversial_graph_coloring
  env_args:
    ai_obs_mode: neighbors
    graph_args:
      graph_type: random_regular
      degree: 3
      chromatic_number: 3
    fixed_agents: 0
    all_agents: 6
    max_steps: 50
    fixed_length: true
    fixed_pos: true
    fixed_network: true
    rewards_args:
      ai:
        avg_coordination: -1
        avg_catch: 1
      ci:
        ind_coordination: 0.5
        avg_coordination: 0.5
        ind_catch: -0.5
        avg_catch: -0.5
