exec:
  command: video
  cores: 6
  hours: 2
  in_dir: runs/technical/latency/train/project_ai_vs_ci__batch_learning_latency__stabilizing_slow_update__lr_0.0001
  memory: 32
  script_name: cpu_torque
exp_id: ebaf3063-cbc5-4700-9bcf-f7c576517bda
job_id: batch_learning_latency__lr_0.0001__project_ai_vs_ci__stabilizing_slow_update
labels:
  batch: learning_latency
  lr: 0.0001
  project: ai_vs_ci
  stabilizing: slow_update
params:
  video_args:
    train:
      mod_episode: 500
