description: >-
  In this experiment ...
grid:
  - - params.environment_args.reward_args:
        ci:
          ind_anticoordination:
            ci: 1
          ind_crosscoordination:
            ci: -1
        ai:
          ind_anticoordination:
            ci: -1
          ind_crosscoordination:
            ci: 1
      labels.rewards: ind_anticoordination
    - params.environment_args.reward_args:
        ci:
          ind_coordination:
            ci: 1
          ind_crosscoordination:
            ci: -1
        ai:
          ind_coordination:
            ci: -1
          ind_crosscoordination:
            ci: 1
      labels.rewards: ind_coordination
    - params.environment_args.reward_args:
        ci:
          global_anticoordination:
            ci: 1
          global_crosscoordination:
            ci: -1
        ai:
          ind_anticoordination:
            ci: -1
          global_crosscoordination:
            ci: 1
      labels.rewards: global_anticoordination
    - params.environment_args.reward_args:
        ci:
          global_coordination:
            ci: 1
          global_crosscoordination:
            ci: -1
        ai:
          global_coordination:
            ci: -1
          global_crosscoordination:
            ci: 1
      labels.rewards: global_coordination
  - params.controller_args.ci.opt_args.lr: [0.001, 0.0001]
    params.controller_args.ai.opt_args.lr: [0.001, 0.0001]
    labels.lr: [0.001, 0.0001]
include:
  - baseconfigs/train/cuda_v1.yml
  - baseconfigs/train/envs/erdos_renyi_20_v1.yml
  - baseconfigs/train/envs/reward_original_v1.yml
  - baseconfigs/train/controller/madql_medium_v1.yml
  - baseconfigs/train/observer/neighbors_simple_v1.yml
  - baseconfigs/train/scheduler/on_off_15000_v1.yml
