params:
  controller_args:
    ai:
      class_name: madqn
      gamma: 0.80
      target_update_freq: 500
      sample_args:
        batch_size: 10
        horizon: 500
      opt_args:
        lr: 0.001
      wrapper_args:
        weight_sharing: true
    ci:
      class_name: madqn
      gamma: 0.80
      target_update_freq: 500
      sample_args:
        batch_size: 10
        horizon: 500
      opt_args:
        lr: 0.001
      wrapper_args:
        weight_sharing: false
